version: '3'
services:
  orbits:
    image: cmsorbits/cms-neso:0.3.3
    environment:
      - NESO_CMS_URL=http://cms
      - NESO_MONGO_USERNAME=cmsuser
      - NESO_MONGO_PASSWORD=notsecure
      - NESO_MONGO_HOST=mongo
