version: '3'
services:
  mongo:
    image: mongo:4.0-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: notsecure
    ports:
      - '27017:27017'
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
